rvm:
  - 1.9.3

notifications:
  recipients:
    - support@typuscmf.com

services:
  - mongodb

branches:
  only:
    - master
    - 3-1-stable

before_script:
  - psql -c 'create database typus_test;' -U postgres

before_install:
  - git submodule update --init --recursive
